---
- name: install aptitude
  apt:
    name: aptitude
    state: present
    update_cache: yes

- include: swap.yml
  when: swap_enabled is defined and swap_enabled == true

- include: tools.yml

- include: locale.yml

